# Generated by Django 4.0.6 on 2022-11-22 06:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file_name', models.CharField(db_index=True, max_length=100)),
                ('zip_file_directory', models.CharField(db_index=True, max_length=100)),
                ('input_path', models.CharField(max_length=500)),
                ('output_path', models.CharField(max_length=500)),
                ('appName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties', models.CharField(max_length=500)),
                ('scope', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2022, 11, 22, 12, 1, 56, 754353))),
                ('source_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MascEngine.sourcecode')),
            ],
        ),
    ]
