# Generated by Django 4.0.6 on 2022-10-10 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MascEngine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processlog',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 11, 38, 16, 726469)),
        ),
    ]
