# Generated by Django 4.0.6 on 2022-11-14 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MascEngine', '0002_processlog_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processlog',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 13, 17, 22, 790178)),
        ),
    ]
