# Generated by Django 4.0.6 on 2022-11-17 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MascEngine', '0003_alter_processlog_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processlog',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 10, 41, 17, 339759)),
        ),
    ]
