# Generated by Django 4.0.6 on 2022-11-22 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MascEngine', '0006_alter_processlog_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processlog',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 4, 52, 56, 941257)),
        ),
    ]
