# Generated by Django 4.0.6 on 2022-08-29 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CipherManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertieslist',
            name='filename',
        ),
    ]
