# Generated by Django 4.0.6 on 2022-08-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CipherManager', '0002_remove_propertieslist_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertieslist',
            name='filename',
            field=models.CharField(db_index=True, default='any.properties', max_length=100),
        ),
    ]
