# Generated by Django 4.0.6 on 2022-11-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PluginsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('filename', models.CharField(db_index=True, default='any.properties', max_length=100)),
                ('compilation', models.CharField(default='false', max_length=200)),
                ('classfile', models.CharField(default='any.class', max_length=200)),
                ('status', models.CharField(default='active', max_length=200)),
                ('path', models.CharField(max_length=500)),
            ],
        ),
    ]
