# Generated by Django 4.0.6 on 2022-11-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginslist',
            name='classfile',
            field=models.CharField(default='any.class', max_length=200),
        ),
        migrations.AddField(
            model_name='pluginslist',
            name='compilation',
            field=models.CharField(default='false', max_length=200),
        ),
        migrations.AddField(
            model_name='pluginslist',
            name='status',
            field=models.CharField(default='active', max_length=200),
        ),
    ]
